// Auto-generated by packages/db/src/seed/scripts/parse-procedures.ts — do not edit by hand.

import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { DOCUMENT_TYPES } from "../data/document-types";
import { FEES } from "../data/fees";
import { OBLIGATIONS } from "../data/obligations";
import { PROCEDURE_TEMPLATES } from "../data/procedure-templates";
import type { SeedFee } from "../data/fees";
import type { SeedObligation } from "../data/obligations";
import type { SeedProcedureTemplate } from "../data/procedure-templates";
import type { SeedRuleCitation } from "../data/rule-citations";

type JsonObject = Record<string, unknown>;

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "../../../../..");
const OUTPUT_PATH = path.resolve(SCRIPT_DIR, "../data/generated/procedures.generated.ts");

const ROOTS: Array<{ agencyId: string; dir: string }> = [
  { agencyId: "RNE", dir: path.join(REPO_ROOT, "docs/RNE Procedures/RNE Procedures") },
  { agencyId: "DGI", dir: path.join(REPO_ROOT, "docs/dgi_procedures") },
  { agencyId: "APII", dir: path.join(REPO_ROOT, "docs/APII Procedures") },
];

const PDF = "application/pdf";
const JPEG = "image/jpeg";
const PNG = "image/png";

// -----------------------------------------------------------------------------
// Text helpers
// -----------------------------------------------------------------------------

function norm(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function slugify(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");
}

function hashKey(value: string): string {
  return createHash("sha256").update(value).digest("hex").slice(0, 12);
}

function truncate(value: string, max: number): string {
  if (value.length <= max) return value;
  const cut = value.slice(0, max);
  const space = cut.lastIndexOf(" ");
  return `${space > max * 0.6 ? cut.slice(0, space) : cut}…`;
}

function stripMarkdown(value: string): string {
  return value
    .replace(/\*\*/g, "")
    .replace(/`/g, "")
    .replace(/^\s*[-*]\s+/, "")
    .replace(/^\s*\[[ x]\]\s*/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

// -----------------------------------------------------------------------------
// Markdown structure
// -----------------------------------------------------------------------------

type Heading = { level: number; title: string; line: number; end: number };

function parseHeadings(lines: string[]): Heading[] {
  const headings: Heading[] = [];

  for (let index = 0; index < lines.length; index += 1) {
    const match = /^(#{1,6})\s+(.*?)\s*$/.exec(lines[index] ?? "");
    if (match && match[1] && match[2]) {
      headings.push({ level: match[1].length, title: match[2], line: index, end: lines.length });
    }
  }

  for (let index = 0; index < headings.length; index += 1) {
    const heading = headings[index];
    if (!heading) continue;
    let end = lines.length;
    for (let next = index + 1; next < headings.length; next += 1) {
      const candidate = headings[next];
      if (candidate && candidate.level <= heading.level) {
        end = candidate.line;
        break;
      }
    }
    heading.end = end;
  }

  return headings;
}

function sectionLines(lines: string[], heading: Heading): string[] {
  return lines.slice(heading.line + 1, heading.end);
}

function isStepContainer(title: string): boolean {
  return /^etapes?$/.test(norm(title));
}

function cleanStepTitle(value: string): string {
  return value
    .replace(/^(Étape|Etape)\s*\d+\s*[—\-–:.]\s*/i, "")
    .replace(/^\d+\s*[.)\-–:]\s*/, "")
    .replace(/\*\*/g, "")
    .replace(/[.:]+$/, "")
    .trim();
}

function bodyToDescription(body: string[], max = 900): string {
  const parts: string[] = [];
  for (const raw of body) {
    const line = stripMarkdown(raw);
    if (!line) continue;
    if (!parts.includes(line)) parts.push(line);
  }
  return truncate(parts.join(" · "), max);
}

type ParsedStep = { titleFr: string; description: string };

function parseNumberedItems(lines: string[]): Array<{ title: string; body: string[] }> {
  const items: Array<{ title: string; body: string[] }> = [];
  let current: { title: string; body: string[] } | null = null;

  for (const raw of lines) {
    const match = /^\s{0,3}(\d+)\.\s+(.*)$/.exec(raw);
    if (match && match[2]) {
      if (current) items.push(current);
      current = { title: match[2].trim(), body: [] };
    } else if (current) {
      current.body.push(raw);
    }
  }

  if (current) items.push(current);
  return items;
}

function parseSteps(lines: string[], headings: Heading[]): ParsedStep[] {
  const containers = headings.filter((heading) => isStepContainer(heading.title));
  const multiple = containers.length > 1;
  const steps: ParsedStep[] = [];

  for (const container of containers) {
    let context = "";
    if (multiple) {
      const parent = [...headings]
        .reverse()
        .find(
          (heading) =>
            heading.line < container.line &&
            heading.level < container.level &&
            !isStepContainer(heading.title),
        );
      context = parent ? cleanStepTitle(parent.title.replace(/^[A-Z]\.\s*/, "")) : "";
    }

    const content = sectionLines(lines, container);
    const subHeadings = headings.filter(
      (heading) =>
        heading.line > container.line &&
        heading.line < container.end &&
        heading.level > container.level,
    );

    if (subHeadings.length > 0) {
      const minLevel = Math.min(...subHeadings.map((heading) => heading.level));
      for (const heading of subHeadings.filter((entry) => entry.level === minLevel)) {
        const title = cleanStepTitle(heading.title);
        const description = bodyToDescription(sectionLines(lines, heading));
        steps.push({
          titleFr: context ? `${context} — ${title}` : title,
          description,
        });
      }
    } else {
      for (const item of parseNumberedItems(content)) {
        const title = cleanStepTitle(item.title);
        steps.push({
          titleFr: context ? `${context} — ${title}` : title,
          description: bodyToDescription(item.body),
        });
      }
    }
  }

  if (steps.length === 0) {
    const etapeHeadings = headings.filter((heading) => /^etape\s*\d+\b/.test(norm(heading.title)));
    if (etapeHeadings.length > 0) {
      for (const heading of etapeHeadings) {
        steps.push({
          titleFr: cleanStepTitle(heading.title),
          description: bodyToDescription(sectionLines(lines, heading)),
        });
      }
    }
  }

  if (steps.length === 0) {
    const excluded =
      /checklist|controle|control|source|delai|piece|objectif|point important|attention|important|resultat|a verifier/i;
    for (const heading of headings) {
      if (isStepContainer(heading.title) || excluded.test(norm(heading.title))) continue;
      const items = parseNumberedItems(sectionLines(lines, heading));
      if (items.length < 2) continue;
      for (const item of items) {
        const title = cleanStepTitle(item.title);
        steps.push({ titleFr: title, description: bodyToDescription(item.body) });
      }
      break;
    }
  }

  return steps;
}

function parseObjective(lines: string[], headings: Heading[]): string {
  const inlineIndex = lines.findIndex((line) => /^\*\*Objectif\s*:\*\*/i.test(line));

  if (inlineIndex >= 0) {
    const collected: string[] = [];
    const first = (lines[inlineIndex] ?? "").replace(/^\*\*Objectif\s*:\*\*\s*/i, "").trim();
    if (first) collected.push(first);
    for (let index = inlineIndex + 1; index < lines.length; index += 1) {
      const line = lines[index] ?? "";
      if (/^#{1,6}\s/.test(line)) break;
      if (!line.trim()) continue;
      collected.push(stripMarkdown(line));
      break;
    }
    return collected.join(" ").trim();
  }

  const heading = headings.find((entry) => norm(entry.title) === "objectif");
  if (!heading) return "";
  return bodyToDescription(sectionLines(lines, heading), 1200);
}

function parseChecklist(lines: string[]): string[] {
  const items: string[] = [];
  for (const raw of lines) {
    const match = /\[[ xX]\]\s*(.+)$/.exec(raw);
    if (!match || !match[1]) continue;
    const item = stripMarkdown(match[1]);
    if (item && !items.includes(item)) items.push(item);
  }
  return items;
}

function parsePieces(lines: string[], headings: Heading[]): string[] {
  const pieces: string[] = [];
  const pieceHeadings = headings.filter((heading) =>
    /pieces principales|pieces a fournir|documents? requis|a preparer/.test(norm(heading.title)),
  );
  const looksLikeDocument =
    /statut|piece|attestation|certificat|copie|extrait|declaration|document|contrat|titre|acte|autorisation|cahier|\bcin\b|passeport|identite|justificatif|bilan|facture|\bpv\b|proces|fiche|dossier|plan|rapport|etats financiers/i;

  for (const heading of pieceHeadings) {
    for (const raw of sectionLines(lines, heading)) {
      const match = /^\s*[-*]\s+(.*)$/.exec(raw);
      if (!match || !match[1]) continue;
      if (/^\s*[-*]\s*\[[ xX]\]/.test(raw)) continue;
      const item = stripMarkdown(match[1]).replace(/\.$/, "");
      if (!item || !looksLikeDocument.test(item)) continue;
      if (!pieces.includes(item)) pieces.push(item);
    }
  }

  return pieces;
}

function parseDelais(lines: string[], headings: Heading[]): string[] {
  const collected: string[] = [];
  const delaiHeadings = headings.filter((heading) => {
    const normalized = norm(heading.title);
    return normalized.includes("delai") || normalized === "repere general";
  });

  for (const heading of delaiHeadings) {
    for (const raw of sectionLines(lines, heading)) {
      const line = stripMarkdown(raw);
      if (line) collected.push(line);
    }
  }

  return collected;
}

function parseSource(lines: string[], headings: Heading[]): string {
  const heading = headings.find((entry) => norm(entry.title) === "source");
  if (!heading) return "";
  return bodyToDescription(sectionLines(lines, heading), 600);
}

function parseTitle(lines: string[]): string {
  const heading = lines.find((line) => /^#\s+/.test(line));
  if (!heading) return "";
  return heading
    .replace(/^#\s+/, "")
    .replace(/^(DGI|APII|RNE)\s*[—\-–:]\s*/i, "")
    .replace(/^\d+\.\s*/, "")
    .trim();
}

function extractUrls(text: string): string[] {
  return [...text.matchAll(/https?:\/\/[^\s)>"']+/g)].map((match) =>
    match[0].replace(/[.,;]+$/, ""),
  );
}

function extractLawRefs(text: string): string[] {
  const patterns = [
    /Loi\s+n[°o]?\s*[\d-]+(?:\s+du\s+[^,;.)\n]+)?/gi,
    /Décret(?:-loi)?\s+n[°o]?\s*[\d-]+(?:\s+du\s+[^,;.)\n]+)?/gi,
    /Code\s+(?:de\s+commerce|de\s+l'IRPP[^,;.\n]*|du\s+travail|des\s+sociétés\s+commerciales)/gi,
    /RNE\s+[A-Z]\s*\d+(?:\.\d+)?/g,
  ];
  const refs: string[] = [];
  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) {
      const ref = match[0].replace(/\s+/g, " ").trim();
      if (ref && !refs.includes(ref)) refs.push(ref);
    }
  }
  return refs;
}

function extractFees(
  delaisLines: string[],
  fullText: string,
): Array<{ amount: string; note: string }> {
  const found: Array<{ amount: string; note: string }> = [];
  const seen = new Set<string>();

  for (const line of delaisLines) {
    if (!line) continue;
    for (const match of line.matchAll(/(\d+(?:[.,]\d+)?)\s*(TND|DT)\b/gi)) {
      const amount = (match[1] ?? "").replace(",", ".");
      if (seen.has(amount)) continue;
      seen.add(amount);
      found.push({ amount, note: truncate(line, 180) });
    }
  }

  if (found.length === 0) {
    for (const line of fullText.split("\n")) {
      const stripped = stripMarkdown(line);
      if (!/redevance|frais|pay|DT\b|TND/i.test(stripped)) continue;
      for (const match of stripped.matchAll(/(\d+(?:[.,]\d+)?)\s*(TND|DT)\b/gi)) {
        const amount = (match[1] ?? "").replace(",", ".");
        if (seen.has(amount)) continue;
        seen.add(amount);
        found.push({ amount, note: truncate(stripped, 180) });
      }
    }
  }

  return found;
}

function extractEstimatedDays(delaisLines: string[], steps: ParsedStep[]): number | null {
  const hints = [
    ...delaisLines,
    ...steps
      .filter((step) => /delai|délai/i.test(step.titleFr))
      .flatMap((step) => [step.titleFr, step.description]),
  ].join(" ");

  const days = /(\d+)\s*jours?\b/i.exec(hints);
  if (days && days[1]) return Number.parseInt(days[1], 10);

  const hours = /(\d+)\s*heures?\b/i.exec(hints);
  if (hours && hours[1]) return Math.ceil(Number.parseInt(hours[1], 10) / 24);

  return null;
}

// -----------------------------------------------------------------------------
// Per-file parse
// -----------------------------------------------------------------------------

type ParsedFile = {
  agencyId: string;
  code: string;
  key: string;
  slug: string;
  relPath: string;
  nameFr: string;
  objective: string;
  steps: ParsedStep[];
  checklist: string[];
  pieces: string[];
  delaisLines: string[];
  sourceText: string;
  rawText: string;
};

const CODE_OVERRIDES: Record<string, { code: string; key: string }> = {
  "RNE/13-changer-dirigeant-societe": {
    code: "changement_gerant",
    key: "procedure_changement_gerant",
  },
};

function parseFile(agencyId: string, filePath: string): ParsedFile {
  const rawText = readFileSync(filePath, "utf8");
  const lines = rawText.split(/\r?\n/);
  const headings = parseHeadings(lines);
  const base = path.basename(filePath, ".md");
  const slug = base.replace(/^\d+[-_]/, "");
  const override = CODE_OVERRIDES[`${agencyId}/${base}`];
  const code = override?.code ?? slugify(slug);
  const key = override?.key ?? `procedure_${agencyId.toLowerCase()}_${code}`;
  const title = parseTitle(lines);
  const pieces = parsePieces(lines, headings);
  const steps = parseSteps(lines, headings);
  const delaisLines = parseDelais(lines, headings);

  return {
    agencyId,
    code,
    key,
    slug,
    relPath: path.relative(REPO_ROOT, filePath),
    nameFr: title,
    objective: parseObjective(lines, headings),
    steps,
    checklist: parseChecklist(lines),
    pieces,
    delaisLines,
    sourceText: parseSource(lines, headings),
    rawText,
  };
}

// -----------------------------------------------------------------------------
// stepType / category / obligations classification
// -----------------------------------------------------------------------------

type StepType = "info" | "form" | "upload" | "payment" | "review" | "submission";

function inferStepType(titleFr: string, description: string): StepType {
  const text = norm(`${titleFr} ${description}`);

  if (/\b(payer|paiement|regler|redevance|droits?|montant du|frais de)\b/.test(text))
    return "payment";
  if (
    /\b(joindre|piece|pieces|justificatif|justificatifs|televers\w*|copie|documents?)\b|deposer les (documents|justificatifs|pieces)/.test(
      text,
    )
  ) {
    return "upload";
  }
  if (/\b(deposer|depot|soumettre|envoyer|envoi|transmettre|transmission|remettre)\b/.test(text)) {
    return "submission";
  }
  if (/\b(remplir|saisir|renseigner|formulaire|declaration|declarer|ecran|fiche)\b/.test(text)) {
    return "form";
  }
  if (
    /\b(verifier|suivre|attendre|consulter|controler|conserver|archiver|identifier|preparer|choisir|selectionner|accomplir|obtenir|recuperer|determiner)\b/.test(
      text,
    )
  ) {
    return "info";
  }
  return "info";
}

const CATEGORY_OVERRIDES: Record<string, string> = {
  reserver_denomination_sociale: "registration",
  immatriculer_nouvelle_entreprise: "registration",
  modifier_informations_entreprise: "modification",
  deposer_etats_financiers_annuels: "declaration",
  fermer_entreprise_radiation: "closure",
  declaration_beneficiaire_effectif: "declaration",
  obtenir_extrait_registre: "certificate",
  verifier_authenticite_extrait: "certificate",
  certificat_non_immatriculation: "certificate",
  certificat_non_faillite: "certificate",
  inscrire_nantissement_ou_leasing: "registration",
  ouvrir_filiale: "registration",
  changement_gerant: "modification",
  declaration_existence_identifiant_fiscal: "registration",
  declaration_mensuelle_fiscale: "declaration",
  declaration_annuelle_irpp_is: "declaration",
  acomptes_provisionnels: "declaration",
  retenue_a_la_source: "declaration",
  certificat_retenue_source: "certificate",
  demande_restitution_tva: "other",
  mise_a_jour_dossier_fiscal: "modification",
  cessation_activite_fiscale: "closure",
  teledeclaration_paiement_en_ligne: "declaration",
  regime_forfaitaire_obligations: "declaration",
  checklist_fiscale_entreprise: "other",
  declaration_projet_investissement: "investment",
  declaration_activite_soumise_autorisation: "investment",
  extension_projet: "investment",
  renouvellement_regime_projet: "investment",
  reconversion_regime_projet: "investment",
  obtenir_attestation_depot_declaration: "certificate",
  creation_entreprise_individuelle_guichet: "registration",
  suivre_dossier_declaration_en_ligne: "other",
  projet_grand_investissement: "investment",
  checklist_declaration_apii: "investment",
};

function inferCategory(code: string): string {
  return CATEGORY_OVERRIDES[code] ?? "other";
}

const OBLIGATION_KEY_BY_PROCEDURE: Record<string, string> = {
  immatriculer_nouvelle_entreprise: "obligation_rne_immatriculation_societe",
  changement_gerant: "obligation_rne_changement_dirigeant",
  deposer_etats_financiers_annuels: "obligation_rne_depot_etats_financiers",
  declaration_beneficiaire_effectif: "obligation_rne_declaration_beneficiaire_effectif",
  fermer_entreprise_radiation: "obligation_rne_dissolution_liquidation",
  ouvrir_filiale: "obligation_rne_etablissement_secondaire",
  declaration_existence_identifiant_fiscal: "obligation_dgi_identifiant_fiscal",
  declaration_mensuelle_fiscale: "obligation_dgi_declaration_fiscale_mensuelle",
  declaration_annuelle_irpp_is: "obligation_dgi_declaration_fiscale_annuelle",
  acomptes_provisionnels: "obligation_dgi_acomptes_provisionnels",
  retenue_a_la_source: "obligation_dgi_retenue_a_la_source",
  regime_forfaitaire_obligations: "obligation_dgi_regime_forfaitaire",
  cessation_activite_fiscale: "obligation_dgi_cessation_activite",
  mise_a_jour_dossier_fiscal: "obligation_dgi_mise_a_jour_dossier_fiscal",
};

type ObligationSpec = {
  agencyId: string;
  code: string;
  key: string;
  nameFr: string;
  periodicity: SeedObligation["periodicity"];
  deadlineRule: JsonObject;
  description: string;
};

const OBLIGATION_SPECS: Record<string, ObligationSpec> = {
  declaration_existence_identifiant_fiscal: {
    agencyId: "DGI",
    code: "identifiant_fiscal",
    key: "obligation_dgi_identifiant_fiscal",
    nameFr: "Déclaration d'existence et identifiant fiscal",
    periodicity: "one_off",
    deadlineRule: { type: "before_activity_start", note: "avant le démarrage de l'activité" },
    description:
      "Déclarer l'activité à l'administration fiscale avant son démarrage et obtenir l'identifiant fiscal.",
  },
  declaration_mensuelle_fiscale: {
    agencyId: "DGI",
    code: "declaration_fiscale_mensuelle",
    key: "obligation_dgi_declaration_fiscale_mensuelle",
    nameFr: "Déclaration fiscale mensuelle (TVA, retenues à la source, FOPROLOS)",
    periodicity: "monthly",
    deadlineRule: {
      type: "monthly",
      physicalDay: 15,
      moralDay: 28,
      note: "personnes physiques : 15 premiers jours du mois ; personnes morales : 28 premiers jours du mois",
    },
    description:
      "Déclarer et payer mensuellement la TVA, les retenues à la source et les autres taxes dues.",
  },
  declaration_annuelle_irpp_is: {
    agencyId: "DGI",
    code: "declaration_fiscale_annuelle",
    key: "obligation_dgi_declaration_fiscale_annuelle",
    nameFr: "Déclaration annuelle de résultats (IRPP / IS)",
    periodicity: "annual",
    deadlineRule: {
      type: "annual",
      reference: "exercice précédent",
      note: "dans le délai légal applicable",
    },
    description: "Déposer la déclaration annuelle IRPP ou IS et régler le solde éventuel.",
  },
  acomptes_provisionnels: {
    agencyId: "DGI",
    code: "acomptes_provisionnels",
    key: "obligation_dgi_acomptes_provisionnels",
    nameFr: "Acomptes provisionnels (3 acomptes)",
    periodicity: "quarterly",
    deadlineRule: {
      type: "installments",
      count: 3,
      rate: 0.3,
      months: [6, 9, 12],
      reference: "impôt dû au titre de l'année précédente",
    },
    description:
      "Préparer et payer trois acomptes provisionnels au cours des 6e, 9e et 12e mois de l'année.",
  },
  retenue_a_la_source: {
    agencyId: "DGI",
    code: "retenue_a_la_source",
    key: "obligation_dgi_retenue_a_la_source",
    nameFr: "Retenue à la source",
    periodicity: "monthly",
    deadlineRule: { type: "monthly", note: "intégrée à la déclaration fiscale correspondante" },
    description:
      "Calculer, déclarer et verser les retenues à la source et délivrer les certificats correspondants.",
  },
  regime_forfaitaire_obligations: {
    agencyId: "DGI",
    code: "regime_forfaitaire",
    key: "obligation_dgi_regime_forfaitaire",
    nameFr: "Obligations du régime forfaitaire",
    periodicity: "annual",
    deadlineRule: {
      type: "annual",
      note: "déclaration annuelle et acomptes selon le régime forfaitaire",
    },
    description:
      "Respecter les obligations déclaratives annuelles et périodiques du régime forfaitaire.",
  },
  cessation_activite_fiscale: {
    agencyId: "DGI",
    code: "cessation_activite",
    key: "obligation_dgi_cessation_activite",
    nameFr: "Déclaration de cessation d'activité",
    periodicity: "one_off",
    deadlineRule: { type: "days_after_event", days: 15, event: "cession_ou_fermeture_definitive" },
    description: "Déclarer l'arrêt définitif ou la cession de l'activité dans les 15 jours.",
  },
  mise_a_jour_dossier_fiscal: {
    agencyId: "DGI",
    code: "mise_a_jour_dossier_fiscal",
    key: "obligation_dgi_mise_a_jour_dossier_fiscal",
    nameFr: "Mise à jour du dossier fiscal",
    periodicity: "event_based",
    deadlineRule: { type: "on_change", note: "lorsqu'un élément du dossier fiscal change" },
    description:
      "Maintenir à jour les informations fiscales de l'entreprise auprès de l'administration.",
  },
};

const OBLIGATION_AR: Record<string, string> = {
  obligation_dgi_identifiant_fiscal: "التصريح بالوجود والمعرّف الجبائي",
  obligation_dgi_declaration_fiscale_mensuelle: "التصريح الجبائي الشهري",
  obligation_dgi_declaration_fiscale_annuelle: "التصريح السنوي بالنتائج",
  obligation_dgi_acomptes_provisionnels: "الدفعات الاحتياطية",
  obligation_dgi_retenue_a_la_source: "الخصم من المصدر",
  obligation_dgi_regime_forfaitaire: "واجبات النظام الجزافي",
  obligation_dgi_cessation_activite: "التصريح بوقف النشاط",
  obligation_dgi_mise_a_jour_dossier_fiscal: "تحيين الملف الجبائي",
};

// -----------------------------------------------------------------------------
// Document types
// -----------------------------------------------------------------------------

type DocEntry = {
  key: string;
  code: string;
  agencyId: string | null;
  nameFr: string;
  nameAr: string;
  description: string;
  acceptedMimeTypes: string[];
  requiredFields: string[];
  validityDays: number | null;
  source: "existing" | "generated";
  tokens: string[];
};

const DOC_STOPWORDS = new Set([
  "document",
  "documents",
  "dossier",
  "dossiers",
  "piece",
  "pieces",
  "information",
  "informations",
  "entreprise",
  "activity",
  "activite",
  "demande",
  "copie",
  "selon",
  "necessaire",
  "necessaires",
  "applicable",
  "applicables",
  "enregistres",
  "enregistre",
]);

function docTokens(nameFr: string): string[] {
  return norm(nameFr)
    .split(" ")
    .filter((token) => token.length >= 5 && !DOC_STOPWORDS.has(token));
}

const GENERIC_DOC_CODES = new Set([
  "cin",
  "passeport",
  "justificatif_adresse",
  "facture",
  "titre_de_propriete",
  "autorisation",
  "cahier_des_charges",
  "cin_carte_de_residence",
  "autorisation_ou_cahier_des_charges",
]);

const CURATED_DOCS: Array<Omit<DocEntry, "source" | "tokens">> = [
  {
    key: "doc_declaration_existence",
    code: "declaration_existence",
    agencyId: "DGI",
    nameFr: "Déclaration d'existence",
    nameAr: "التصريح بالوجود",
    description: "Formulaire de déclaration d'existence déposé auprès de l'administration fiscale.",
    acceptedMimeTypes: [PDF],
    requiredFields: [],
    validityDays: null,
  },
  {
    key: "doc_carte_identification_fiscale",
    code: "carte_identification_fiscale",
    agencyId: "DGI",
    nameFr: "Carte d'identification fiscale",
    nameAr: "بطاقة التعريف الجبائي",
    description: "Carte d'identification fiscale délivrée par la DGI.",
    acceptedMimeTypes: [PDF, JPEG, PNG],
    requiredFields: [],
    validityDays: null,
  },
  {
    key: "doc_autorisation",
    code: "autorisation",
    agencyId: null,
    nameFr: "Autorisation administrative",
    nameAr: "الترخيص الإداري",
    description: "Autorisation préalable requise pour les activités réglementées.",
    acceptedMimeTypes: [PDF],
    requiredFields: [],
    validityDays: null,
  },
  {
    key: "doc_cahier_des_charges",
    code: "cahier_des_charges",
    agencyId: null,
    nameFr: "Cahier des charges",
    nameAr: "كراس الشروط",
    description: "Cahier des charges signé et déposé pour les activités soumises à autorisation.",
    acceptedMimeTypes: [PDF],
    requiredFields: [],
    validityDays: null,
  },
  {
    key: "doc_actes_constitutifs",
    code: "actes_constitutifs",
    agencyId: "RNE",
    nameFr: "Actes constitutifs enregistrés",
    nameAr: "الوثائق التأسيسية المسجلة",
    description: "Actes constitutifs de la société enregistrés à la recette des finances.",
    acceptedMimeTypes: [PDF],
    requiredFields: [],
    validityDays: null,
  },
  {
    key: "doc_etats_financiers",
    code: "etats_financiers",
    agencyId: "RNE",
    nameFr: "États financiers",
    nameAr: "القوائم المالية",
    description: "États financiers annuels approuvés de l'exercice.",
    acceptedMimeTypes: [PDF],
    requiredFields: [],
    validityDays: null,
  },
  {
    key: "doc_attestation_depot_declaration",
    code: "attestation_depot_declaration",
    agencyId: "APII",
    nameFr: "Attestation de dépôt de déclaration (ADD)",
    nameAr: "شهادة إيداع التصريح",
    description: "Attestation délivrée par l'APII après dépôt de la déclaration d'investissement.",
    acceptedMimeTypes: [PDF],
    requiredFields: [],
    validityDays: null,
  },
];

function docNameFromPiece(piece: string): string {
  let value = piece.split(",")[0]?.trim() ?? piece;
  value = value
    .replace(/\s+(selon|si|pour|lorsqu|en cas|dans le cas|le cas)\b.*$/i, "")
    .replace(/\s*\/\s*/g, " / ")
    .replace(/\.$/, "")
    .trim();
  if (value.length > 80) value = truncate(value, 80).replace(/…$/, "").trim();
  return value;
}

function buildDocumentRegistry(files: ParsedFile[]): {
  registry: DocEntry[];
  generated: DocEntry[];
} {
  const registry: DocEntry[] = [];
  const byName = new Set<string>();
  const byCode = new Set<string>();

  for (const doc of DOCUMENT_TYPES) {
    const entry: DocEntry = { ...doc, source: "existing", tokens: docTokens(doc.nameFr) };
    registry.push(entry);
    byName.add(norm(doc.nameFr));
    byCode.add(doc.code);
  }

  const generated: DocEntry[] = [];

  for (const curated of CURATED_DOCS) {
    if (byCode.has(curated.code) || byName.has(norm(curated.nameFr))) continue;
    const entry: DocEntry = { ...curated, source: "generated", tokens: docTokens(curated.nameFr) };
    registry.push(entry);
    generated.push(entry);
    byName.add(norm(curated.nameFr));
    byCode.add(curated.code);
  }

  for (const file of files) {
    for (const piece of file.pieces) {
      const nameFr = docNameFromPiece(piece);
      if (!nameFr) continue;
      const normalized = norm(nameFr);
      if (byName.has(normalized)) continue;
      const code = slugify(nameFr);
      if (!code || byCode.has(code)) continue;
      const agencyId = GENERIC_DOC_CODES.has(code) ? null : file.agencyId;
      const entry: DocEntry = {
        key: `doc_${code}`,
        code,
        agencyId,
        nameFr,
        nameAr: docArabic(nameFr) ?? nameFr,
        description: `Pièce requise pour les formalités ${file.agencyId}.`,
        acceptedMimeTypes: /cin|passeport|identite|justificatif|facture/i.test(code)
          ? [PDF, JPEG, PNG]
          : [PDF],
        requiredFields: [],
        validityDays: null,
        source: "generated",
        tokens: docTokens(nameFr),
      };
      registry.push(entry);
      generated.push(entry);
      byName.add(normalized);
      byCode.add(code);
    }
  }

  return { registry, generated };
}

const DOC_SYNONYMS: Array<[RegExp, string]> = [
  [/\bnomination\b/, "pv_nomination_gerant"],
  [/\bproces verbal\b|\bpv d assemblee\b/, "pv_assemblee_generale"],
  [/\bbeneficiaire effectif\b/, "declaration_beneficiaire"],
  [
    /\bcarte d identification fiscale\b|\bcarte fiscale\b|\bidentifiant fiscal\b/,
    "carte_identification_fiscale",
  ],
  [/\bdeclaration d existence\b/, "declaration_existence"],
  [/\battestation de depot\b|\badd\b/, "attestation_depot_declaration"],
  [/\bcahier des charges\b/, "cahier_des_charges"],
  [/\bactes constitutifs\b|\bstatuts enregistres\b/, "actes_constitutifs"],
  [/\bstatuts?\b/, "statuts"],
  [/\bcarte d identite\b|\bpiece d identite\b|\bcin\b|\bcarte nationale\b/, "cin"],
  [/\bpasseport\b/, "passeport"],
  [
    /\bjustificatif de domicile\b|\btitre de propriete\b|\bcontrat de location\b|\bbail\b/,
    "justificatif_adresse",
  ],
  [/\battestation bancaire\b|\bdepot de capital\b|\bcompte bloque\b/, "attestation_banque"],
  [/\betats financiers\b|\bbilan\b/, "etats_financiers"],
  [/\bextraits?\b/, "rne_extrait"],
  [/\bautorisation\b/, "autorisation"],
];

function matchDocumentType(
  text: string,
  registry: DocEntry[],
): { key: string | null; strong: boolean } {
  const normalized = ` ${norm(text)} `;

  for (const [pattern, code] of DOC_SYNONYMS) {
    if (pattern.test(normalized)) {
      const found = registry.find((entry) => entry.code === code);
      if (found) return { key: found.key, strong: true };
    }
  }

  let best: { key: string; score: number } | null = null;
  for (const entry of registry) {
    let score = 0;
    for (const token of entry.tokens) {
      if (normalized.includes(` ${token} `) || normalized.includes(` ${token}s `))
        score += token.length;
    }
    if (score > 0 && (!best || score > best.score)) best = { key: entry.key, score };
  }

  return { key: best?.key ?? null, strong: false };
}

// -----------------------------------------------------------------------------
// Arabic best-effort
// -----------------------------------------------------------------------------

const TEMPLATE_AR: Record<string, string> = {
  reserver_denomination_sociale: "حجز التسمية الاجتماعية",
  immatriculer_nouvelle_entreprise: "تسجيل مؤسسة جديدة",
  modifier_informations_entreprise: "تحيين معلومات المؤسسة",
  deposer_etats_financiers_annuels: "إيداع القوائم المالية السنوية",
  fermer_entreprise_radiation: "غلق المؤسسة وشطبها",
  declaration_beneficiaire_effectif: "التصريح بالمستفيد الحقيقي",
  obtenir_extrait_registre: "الحصول على مضمون السجل",
  verifier_authenticite_extrait: "التحقق من صحة وثيقة السجل",
  certificat_non_immatriculation: "شهادة عدم التسجيل",
  certificat_non_faillite: "شهادة عدم الإفلاس",
  inscrire_nantissement_ou_leasing: "ترسيم الرهن أو الإيجار المالي",
  ouvrir_filiale: "فتح فرع أو مؤسسة ثانوية",
  changement_gerant: "تغيير المتصرف",
  declaration_existence_identifiant_fiscal: "التصريح بالوجود والمعرّف الجبائي",
  declaration_mensuelle_fiscale: "التصريح الجبائي الشهري",
  declaration_annuelle_irpp_is: "التصريح السنوي بالضريبة على الدخل أو الشركات",
  acomptes_provisionnels: "الدفعات الاحتياطية",
  retenue_a_la_source: "الخصم من المصدر",
  certificat_retenue_source: "شهادة الخصم من المصدر",
  demande_restitution_tva: "طلب استرجاع فائض الأداء على القيمة المضافة",
  mise_a_jour_dossier_fiscal: "تحيين الملف الجبائي",
  cessation_activite_fiscale: "التصريح بوقف النشاط الجبائي",
  teledeclaration_paiement_en_ligne: "التصريح والدفع الإلكتروني",
  regime_forfaitaire_obligations: "واجبات النظام الجزافي",
  checklist_fiscale_entreprise: "قائمة مراجعة الواجبات الجبائية",
  declaration_projet_investissement: "التصريح بمشروع استثمار",
  declaration_activite_soumise_autorisation: "التصريح بنشاط خاضع للترخيص",
  extension_projet: "التصريح بتوسيع مشروع",
  renouvellement_regime_projet: "تجديد نظام المشروع",
  reconversion_regime_projet: "تحويل نظام المشروع",
  obtenir_attestation_depot_declaration: "الحصول على شهادة إيداع التصريح",
  creation_entreprise_individuelle_guichet: "إحداث مؤسسة فردية عبر الشباك الموحد",
  suivre_dossier_declaration_en_ligne: "متابعة ملف التصريح عبر الإنترنت",
  projet_grand_investissement: "مشروع استثمار كبير",
  checklist_declaration_apii: "قائمة مراجعة التصريح",
};

const DOC_AR: Record<string, string> = {
  declaration_existence: "التصريح بالوجود",
  carte_identification_fiscale: "بطاقة التعريف الجبائي",
  autorisation: "الترخيص الإداري",
  cahier_des_charges: "كراس الشروط",
  actes_constitutifs: "الوثائق التأسيسية المسجلة",
  etats_financiers: "القوائم المالية",
  attestation_depot_declaration: "شهادة إيداع التصريح",
  declaration_existence_identifiant_fiscal: "التصريح بالوجود والمعرّف الجبائي",
  titre_de_propriete: "سند الملكية",
  cin_carte_de_residence: "بطاقة التعريف الوطنية / بطاقة الإقامة",
  declaration_existence_formulaire: "استمارة التصريح بالوجود",
  autorisation_cahier_des_charges: "الترخيص أو كراس الشروط",
  autorisation_ou_cahier_des_charges: "الترخيص أو كراس الشروط",
  actes_constitutifs_enregistres: "الوثائق التأسيسية المسجلة",
};

function docArabic(nameFr: string): string | null {
  return DOC_AR[slugify(nameFr)] ?? null;
}

const VERB_AR: Record<string, string> = {
  preparer: "إعداد",
  verifier: "التحقق من",
  deposer: "إيداع",
  payer: "دفع",
  regler: "تسوية",
  remplir: "تعبئة",
  saisir: "إدخال",
  identifier: "تحديد",
  choisir: "اختيار",
  selectionner: "اختيار",
  conserver: "حفظ",
  obtenir: "الحصول على",
  suivre: "متابعة",
  soumettre: "إرسال",
  joindre: "إرفاق",
  acceder: "الوصول إلى",
  ouvrir: "فتح",
  creer: "إنشاء",
  decider: "اتخاذ قرار",
  effectuer: "إجراء",
  rassembler: "جمع",
  mettre: "تحيين",
  telecharger: "تحميل",
  archiver: "أرشفة",
  repondre: "الرد على",
  completer: "استكمال",
  contacter: "الاتصال بـ",
  determiner: "تحديد",
  utiliser: "استخدام",
  enregistrer: "تسجيل",
  valider: "المصادقة على",
  integrer: "إدراج",
  calculer: "احتساب",
};

const PHRASE_AR: Record<string, string> = {
  "choisir le nom": "اختيار الاسم",
  "acceder au service de reservation": "الوصول إلى خدمة الحجز",
  "saisir les informations": "إدخال المعلومات",
  "soumettre la demande": "إرسال الطلب",
  "obtenir et conserver le certificat": "الحصول على الشهادة وحفظها",
  "obtenir la carte d identification fiscale": "الحصول على بطاقة التعريف الجبائي",
  "preparer votre piece d identite": "إعداد بطاقة التعريف",
  "reserver la denomination": "حجز التسمية",
  "preparer les statuts": "إعداد النظام الأساسي",
  "faire enregistrer les statuts a la recette des finances": "تسجيل النظام الأساسي بقباضة المالية",
  "preparer les pieces d identite des dirigeants": "إعداد بطاقات تعريف المتصرفين",
  "preparer la declaration du beneficiaire effectif": "إعداد التصريح بالمستفيد الحقيقي",
  "deposer le dossier aupres du rne": "إيداع الملف لدى السجل الوطني للمؤسسات",
  "payer la redevance": "دفع المعاليم",
  "verifier l acceptation et la publication": "التحقق من القبول والنشر",
  "identifier exactement ce qui a change": "تحديد ما تغيّر بدقة",
  "identifier le justificatif necessaire": "تحديد المؤيد اللازم",
  "preparer les documents": "إعداد الوثائق",
  "acceder au service de modification du rne": "الوصول إلى خدمة تحيين السجل الوطني للمؤسسات",
  "selectionner la modification concernee": "اختيار التحيين المعني",
  "deposer les justificatifs": "إيداع المؤيدات",
  "verifier la mise a jour": "التحقق من التحيين",
  "cloturer l exercice comptable": "غلق السنة المالية",
  "preparer les etats financiers": "إعداد القوائم المالية",
  "faire approuver les etats financiers": "المصادقة على القوائم المالية",
  "preparer le pv d approbation": "إعداد محضر المصادقة",
  "verifier le dossier": "التحقق من الملف",
  "acceder au service de depot": "الوصول إلى خدمة الإيداع",
  "deposer les documents": "إيداع الوثائق",
  "conserver la preuve": "حفظ الإثبات",
  "decider la dissolution": "اتخاذ قرار الحل",
  "nommer le liquidateur": "تعيين المصفّي",
  "realiser la liquidation": "إجراء التصفية",
  "cloturer la liquidation": "غلق التصفية",
  "demander la radiation": "طلب الشطب",
  "identifier le ou les beneficiaires effectifs": "تحديد المستفيد أو المستفيدين الحقيقيين",
  "rassembler les informations necessaires": "جمع المعلومات اللازمة",
  "acceder au service rne": "الوصول إلى خدمة السجل الوطني للمؤسسات",
  "saisir la declaration": "إدخال التصريح",
  "soumettre et payer la redevance applicable": "إرسال التصريح ودفع المعاليم المستوجبة",
  "preparer l identifiant de l entreprise": "إعداد معرّف المؤسسة",
  "choisir le type d extrait": "اختيار نوع المضمون",
  "acceder au service d extrait du registre": "الوصول إلى خدمة مضمون السجل",
  "verifier les informations affichees": "التحقق من المعلومات المعروضة",
  "telecharger et conserver le document": "تحميل الوثيقة وحفظها",
  "recuperer le document a verifier": "الحصول على الوثيقة المطلوب التحقق منها",
  "ouvrir le service de verification": "فتح خدمة التحقق",
  "saisir les informations demandees": "إدخال المعلومات المطلوبة",
  "comparer le resultat": "مقارنة النتيجة",
  "conserver la preuve de verification": "حفظ إثبات التحقق",
  "determiner le besoin": "تحديد الحاجة",
  "preparer les informations d identification": "إعداد معلومات التعريف",
  "effectuer la demande aupres du rne": "تقديم الطلب لدى السجل الوطني للمؤسسات",
  "verifier le certificat": "التحقق من الشهادة",
  "verifier que le certificat est requis": "التحقق من ضرورة الشهادة",
  "identifier l entreprise": "تحديد المؤسسة",
  "controler le document recu": "مراقبة الوثيقة المتحصّل عليها",
  "conserver le certificat": "حفظ الشهادة",
  "identifier l operation": "تحديد العملية",
  "preparer l acte enregistre": "إعداد العقد المسجّل",
  "respecter le delai": "احترام الأجل",
  "deposer la demande": "إيداع الطلب",
  "conserver la preuve d inscription": "حفظ إثبات الترسيم",
  "decider l ouverture": "اتخاذ قرار الفتح",
  "preparer les informations": "إعداد المعلومات",
  "identifier la formalite correcte": "تحديد الإجراء الصحيح",
  "verifier l enregistrement": "التحقق من الترسيم",
  "prendre la decision": "اتخاذ القرار",
  "identifier le changement": "تحديد التغيير",
  "preparer les informations du nouveau dirigeant": "إعداد معلومات المتصرف الجديد",
  "deposer la modification": "إيداع التحيين",
  "verifier le registre": "التحقق من السجل",
};

const NOUN_AR: Record<string, string> = {
  "declaration annuelle": "التصريح السنوي",
  "declaration mensuelle": "التصريح الشهري",
  "declaration fiscale": "التصريح الجبائي",
  "declaration de cessation": "التصريح بوقف النشاط",
  "declaration d existence": "التصريح بالوجود",
  "retenue a la source": "الخصم من المصدر",
  "resultat fiscal": "النتيجة الجبائية",
  "credit de tva": "فائض الأداء على القيمة المضافة",
  "cahier des charges": "كراس الشروط",
  "beneficiaire effectif": "المستفيد الحقيقي",
  "redevance applicable": "المعاليم المستوجبة",
  "pieces justificatives": "الوثائق المؤيدة",
  "montant du": "المبلغ المستوجب",
  declarations: "التصريحات",
  declaration: "التصريح",
  redevance: "المعاليم",
  documents: "الوثائق",
  document: "الوثيقة",
  pieces: "الوثائق",
  justificatifs: "المؤيدات",
  justificatif: "المؤيد",
  informations: "المعلومات",
  statuts: "النظام الأساسي",
  dossier: "الملف",
  certificat: "الشهادة",
  attestation: "الشهادة",
  preuves: "الإثباتات",
  preuve: "الإثبات",
  comptabilite: "المحاسبة",
  exercice: "السنة المالية",
  impot: "الضريبة",
  retenue: "الخصم",
  acomptes: "الدفعات",
  acompte: "الدفعة",
  entreprise: "المؤسسة",
  projet: "المشروع",
  activite: "النشاط",
  dirigeant: "المتصرف",
  extrait: "المضمون",
  registre: "السجل",
  autorisation: "الترخيص",
  equipements: "التجهيزات",
  financement: "التمويل",
  emplois: "مواضع الشغل",
  investissement: "الاستثمار",
  bureau: "المكتب",
  service: "المصلحة",
  societe: "الشركة",
  montant: "المبلغ",
};

function stripLeadVerb(value: string): string {
  return value
    .replace(
      /^(preparer|verifier|deposer|payer|regler|remplir|saisir|identifier|choisir|selectionner|conserver|obtenir|suivre|soumettre|joindre|acceder|ouvrir|creer|decider|effectuer|rassembler|mettre|telecharger|archiver|repondre|completer|contacter|determiner|utiliser|enregistrer|valider|integrer|calculer)\s+/i,
      "",
    )
    .trim();
}

function longestNounMatch(value: string): string | null {
  const padded = ` ${value} `;
  let best: { arabic: string; length: number } | null = null;
  for (const [noun, arabic] of Object.entries(NOUN_AR)) {
    if (padded.includes(` ${noun} `) && (!best || noun.length > best.length)) {
      best = { arabic, length: noun.length };
    }
  }
  return best?.arabic ?? null;
}

function stepArabic(titleFr: string): string {
  const normalized = norm(titleFr);
  const exact = PHRASE_AR[normalized];
  if (exact) return exact;

  if (titleFr.includes(" — ")) {
    const parts = titleFr.split(" — ");
    const context = parts[0] ?? "";
    const suffix = parts.slice(1).join(" — ");
    const suffixArabic = stepArabic(suffix);
    if (suffixArabic !== suffix) return `${suffixArabic} (${context})`;
    return titleFr;
  }

  const verbMatch = /^([a-zA-Z]+)\s+(.*)$/.exec(norm(titleFr));
  if (verbMatch && verbMatch[1] && verbMatch[2]) {
    const verb = VERB_AR[verbMatch[1]];
    if (verb) {
      const rest = stripLeadVerb(normalized);
      const noun = longestNounMatch(rest);
      if (noun) return `${verb} ${noun}`;
    }
  }

  return titleFr;
}

// -----------------------------------------------------------------------------
// Rule citations
// -----------------------------------------------------------------------------

function legalArticle(ref: string): string | null {
  const match = /(\d+(?:\.\d+)?)/.exec(ref);
  return match?.[1] ?? null;
}

function buildCitations(file: ParsedFile): SeedRuleCitation[] {
  const citations: SeedRuleCitation[] = [];
  const seen = new Set<string>();

  if (file.sourceText) {
    const urls = extractUrls(file.sourceText);
    const key = `gen_src_${file.agencyId}_${file.code}`;
    citations.push({
      key,
      source: file.sourceText.split(/\s{2,}|\.\s/)[0]?.trim() || file.sourceText,
      article: legalArticle(file.sourceText),
      titleFr: `${file.nameFr} — source`,
      titleAr: "",
      textFr: file.sourceText,
      textAr: "",
      url: urls[0] ?? null,
      effectiveFrom: null,
      effectiveTo: null,
    });
    seen.add(key);
  }

  for (const ref of extractLawRefs(file.rawText)) {
    const key = `gen_law_${hashKey(norm(ref))}`;
    if (seen.has(key)) continue;
    seen.add(key);
    citations.push({
      key,
      source: ref,
      article: legalArticle(ref),
      titleFr: "Référence légale",
      titleAr: "",
      textFr: ref,
      textAr: "",
      url: extractUrls(file.rawText)[0] ?? null,
      effectiveFrom: null,
      effectiveTo: null,
    });
  }

  return citations;
}

// -----------------------------------------------------------------------------
// Main build
// -----------------------------------------------------------------------------

function build(): void {
  const files: ParsedFile[] = [];
  for (const root of ROOTS) {
    let entries: string[] = [];
    try {
      entries = readdirSync(root.dir)
        .filter((entry) => entry.endsWith(".md"))
        .sort();
    } catch {
      continue;
    }
    for (const entry of entries) {
      files.push(parseFile(root.agencyId, path.join(root.dir, entry)));
    }
  }

  const { registry, generated: generatedDocs } = buildDocumentRegistry(files);
  const existingTemplateKeys = new Set(PROCEDURE_TEMPLATES.map((template) => template.key));
  const existingFeeTemplateKeys = new Set(
    FEES.map((fee) => fee.procedureTemplateKey).filter((key): key is string => Boolean(key)),
  );

  const generatedTemplates: SeedProcedureTemplate[] = [];
  const generatedObligationsMap = new Map<string, SeedObligation>();
  const generatedCitations = new Map<string, SeedRuleCitation>();
  const generatedFees: SeedFee[] = [];

  let arTemplate = 0;
  let arStepFull = 0;
  let arStepFallback = 0;
  let stepCount = 0;
  const warnings: string[] = [];

  for (const file of files) {
    const citations = buildCitations(file);
    for (const citation of citations) generatedCitations.set(citation.key, citation);

    const obligationSpec = OBLIGATION_SPECS[file.code];
    let obligationKey: string | null = OBLIGATION_KEY_BY_PROCEDURE[file.code] ?? null;
    if (obligationSpec && obligationKey === null) obligationKey = obligationSpec.key;

    if (obligationSpec) {
      const base = OBLIGATIONS.find(
        (obligation) =>
          obligation.agencyId === obligationSpec.agencyId &&
          obligation.code === obligationSpec.code,
      );
      const citationKeys = citations.length > 0 ? [citations[0]!.key] : [];
      generatedObligationsMap.set(obligationSpec.key, {
        key: obligationSpec.key,
        agencyId: obligationSpec.agencyId,
        code: obligationSpec.code,
        nameFr: base?.nameFr ?? obligationSpec.nameFr,
        nameAr: base?.nameAr ?? OBLIGATION_AR[obligationSpec.key] ?? obligationSpec.nameFr,
        description: obligationSpec.description,
        legalBasis: base?.legalBasis ?? file.sourceText ?? `Documentation ${file.agencyId}`,
        periodicity: obligationSpec.periodicity,
        deadlineRule: obligationSpec.deadlineRule,
        penaltySummary: base?.penaltySummary ?? "",
        appliesTo: base?.appliesTo ?? {
          entityTypes: ["company", "individual"],
          awareness: true,
          authority: file.agencyId,
        },
        citationKeys: Array.from(new Set([...(base?.citationKeys ?? []), ...citationKeys])),
      });
    }

    const hasArabic = Boolean(TEMPLATE_AR[file.code]);
    const nameAr = TEMPLATE_AR[file.code] ?? file.nameFr;
    if (hasArabic) arTemplate += 1;
    else warnings.push(`${file.relPath}: no Arabic template title`);

    const steps: SeedProcedureTemplate["steps"] = file.steps.map((step, index) => {
      const position = index + 1;
      const stepType = inferStepType(step.titleFr, step.description);
      const docMatch = matchDocumentType(`${step.titleFr} ${step.description}`, registry);
      const requiredDocumentTypeKey =
        docMatch.strong || stepType === "upload" ? docMatch.key : null;
      const titleAr = stepArabic(step.titleFr);
      stepCount += 1;
      if (titleAr !== step.titleFr) arStepFull += 1;
      else arStepFallback += 1;

      return {
        key: `${file.key}__step_${position}`,
        position,
        code: `step_${position}`,
        titleFr: step.titleFr,
        titleAr,
        description: step.description,
        stepType,
        requiredDocumentTypeKey,
        formSchema: null,
        isOptional: false,
        citationKeys: [],
      };
    });

    const reviewPosition = steps.length + 1;

    if (file.steps.length === 0) {
      warnings.push(`${file.relPath}: no numbered étapes found (checklist-only document)`);
    }

    steps.push({
      key: `${file.key}__step_${reviewPosition}`,
      position: reviewPosition,
      code: `step_${reviewPosition}`,
      titleFr: "Contrôles avant envoi",
      titleAr: "الرقابة قبل الإرسال",
      description: file.checklist.join(" · "),
      stepType: "review",
      requiredDocumentTypeKey: null,
      formSchema: { version: 1, fields: [], checklist: file.checklist },
      isOptional: false,
      citationKeys: citations.map((citation) => citation.key),
    });

    const estimatedDays = extractEstimatedDays(file.delaisLines, file.steps);

    generatedTemplates.push({
      key: file.key,
      agencyId: file.agencyId,
      obligationKey,
      code: file.code,
      nameFr: file.nameFr || file.code,
      nameAr,
      description: file.objective || file.nameFr,
      category: inferCategory(file.code),
      estimatedDays,
      steps,
    });

    if (existingTemplateKeys.has(file.key)) {
      warnings.push(
        `${file.relPath}: template key collides with hand-written seed template (${file.key})`,
      );
    }

    const fees = extractFees(file.delaisLines, file.rawText);
    fees.forEach((fee, index) => {
      if (existingFeeTemplateKeys.has(file.key)) return;
      generatedFees.push({
        key: `fee_gen_${file.agencyId.toLowerCase()}_${file.code}_${index + 1}`,
        agencyId: file.agencyId,
        procedureTemplateKey: file.key,
        obligationKey,
        label: `Frais — ${truncate(fee.note || file.nameFr, 160)}`,
        amount: Number.parseFloat(fee.amount).toFixed(3),
        currency: "TND",
        logic: { type: "fixed", note: fee.note, source: file.relPath },
      });
    });
  }

  const emittedDocs = generatedDocs;

  const header = [
    "// AUTO-GENERATED FILE — produced by scripts/parse-procedures.ts.",
    "// Run `pnpm -F @nationa/db parse:procedures` to regenerate after editing docs/.",
    "",
    'import type { SeedDocumentType } from "../document-types";',
    'import type { SeedFee } from "../fees";',
    'import type { SeedObligation } from "../obligations";',
    'import type { SeedProcedureTemplate } from "../procedure-templates";',
    'import type { SeedRuleCitation } from "../rule-citations";',
    "",
  ].join("\n");

  const body = [
    `export const GENERATED_PROCEDURE_TEMPLATES: SeedProcedureTemplate[] = ${JSON.stringify(generatedTemplates, null, 2)};`,
    "",
    `export const GENERATED_DOCUMENT_TYPES: SeedDocumentType[] = ${JSON.stringify(emittedDocs, null, 2)};`,
    "",
    `export const GENERATED_OBLIGATIONS: SeedObligation[] = ${JSON.stringify([...generatedObligationsMap.values()], null, 2)};`,
    "",
    `export const GENERATED_FEES: SeedFee[] = ${JSON.stringify(generatedFees, null, 2)};`,
    "",
    `export const GENERATED_RULE_CITATIONS: SeedRuleCitation[] = ${JSON.stringify([...generatedCitations.values()], null, 2)};`,
    "",
  ].join("\n");

  mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, `${header}${body}`, "utf8");

  const stats = {
    files: files.length,
    templates: generatedTemplates.length,
    steps: stepCount + generatedTemplates.length,
    stepsFromDocs: stepCount,
    documentTypes: emittedDocs.length,
    obligations: generatedObligationsMap.size,
    fees: generatedFees.length,
    citations: generatedCitations.size,
    arabicTemplates: `${arTemplate}/${files.length}`,
    arabicStepTitles: `${arStepFull}/${stepCount}`,
    arabicStepFallback: arStepFallback,
  };

  console.log("[parse-procedures] generated", path.relative(REPO_ROOT, OUTPUT_PATH));
  console.log(JSON.stringify(stats, null, 2));
  if (warnings.length > 0) {
    console.log(`[parse-procedures] ${warnings.length} warning(s):`);
    for (const warning of warnings) console.log(`  - ${warning}`);
  }
}

build();
